# SPDX-FileCopyrightText: 2026 Gabriel Santos de Souza <gabriel.santosdesouza@dcomp.ufs.br>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
cargo-dist-version = "0.32.0"
ci = "github"
installers = []
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
hosting = "github"
allow-dirty = ["ci"]
