# SPDX-FileCopyrightText: 2026 Gabriel Santos de Souza <gabriel.santosdesouza@dcomp.ufs.br>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "any2nix-cli"
version = "0.1.0"
edition = "2024"
license.workspace = true
description = "Command-line application for translating from various formats to Nix."

[dependencies]
any2nix.workspace = true
