# SPDX-FileCopyrightText: 2026 Gabriel Santos de Souza <gabriel.santosdesouza@dcomp.ufs.br>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
authors.workspace = true
categories = ["command-line-utilities", "config", "development-tools"]
description = "Command-line application for translating from various formats to Nix."
edition = "2024"
keywords = ["cli", "config", "converter", "nix", "serde"]
license.workspace = true
name = "any2nix-cli"
repository.workspace = true
version = "0.1.0"

[dependencies]
any2nix.workspace = true
