# SPDX-FileCopyrightText: 2026 Gabriel Santos de Souza <gabriel.santosdesouza@dcomp.ufs.br>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
authors.workspace = true
categories = ["command-line-utilities", "config", "development-tools"]
description = "Command-line interface for translating from various formats to Nix."
edition = "2024"
keywords = ["cli", "config", "converter", "nix", "serde"]
license.workspace = true
name = "any2nix-cli"
repository.workspace = true
version = "0.1.1"

[[bin]]
name = "any2nix"
path = "src/main.rs"

[dependencies]
any2nix = { features = ["clap"], workspace = true }
clap = { features = ["derive"], version = "4.6.6" }
clap_complete = "4.6.9"
clap_mangen = "0.3.3"

[features]
default = ["ini", "json", "toml", "yaml"]
ini = ["any2nix/ini"]
json = ["any2nix/json"]
toml = ["any2nix/toml"]
yaml = ["any2nix/yaml"]

[dev-dependencies]
trycmd = "1.2.1"
