# SPDX-FileCopyrightText: 2026 Gabriel Santos de Souza <gabriel.santosdesouza@dcomp.ufs.br>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
authors.workspace = true
categories = ["web-programming", "web-programming::http-server"]
description = """
JSON-based server that can be used as an API for translating from different
formats to Nix.
"""
edition = "2024"
keywords = ["api", "converter", "http", "json", "nix"]
license.workspace = true
name = "any2nix-api"
repository.workspace = true
version = "0.1.0"

[dependencies]
any2nix.workspace = true
axum = "0.8.9"
serde = "1.0.229"
tokio = { features = ["macros", "rt-multi-thread"], version = "1.53.1" }
tower-http = { features = ["trace"], optional = true, version = "0.7.1" }
tracing = { optional = true, version = "0.1.44" }
tracing-subscriber = { features = [
  "env-filter",
], optional = true, version = "0.3.23" }
utoipa = { features = ["axum_extras"], optional = true, version = "5.5.0" }
utoipa-swagger-ui = { features = [
  "axum",
  "debug-embed",
], optional = true, version = "9.0.2" }

[features]
default = ["ini", "json", "toml", "yaml"]
full = ["ini", "json", "toml", "trace", "utoipa", "utoipa-swagger-ui", "yaml"]
ini = ["any2nix/ini"]
json = ["any2nix/json"]
toml = ["any2nix/toml"]
trace = ["dep:tower-http", "dep:tracing", "dep:tracing-subscriber"]
utoipa = ["any2nix/utoipa", "dep:utoipa"]
utoipa-swagger-ui = ["dep:utoipa-swagger-ui", "utoipa"]
yaml = ["any2nix/yaml"]
